services:
  node-1:
    image: ontotext/graphdb:10.8.11
    ports:
      - "7201:7201"
      - "7301:7301"
    environment:
      GDB_JAVA_OPTS: >-
        -Dgraphdb.auth.token.secret=123456
        -Dgraphdb.connector.port=7201
        -Dgraphdb.hostname=first.127.0.0.1.nip.io
    volumes:
      - "${GRAPHDB_LICENSE}:/opt/graphdb/home/conf/graphdb.license:ro"
    extra_hosts:
      - "first.127.0.0.1.nip.io:host-gateway"
      - "second.127.0.0.1.nip.io:host-gateway"
      - "third.127.0.0.1.nip.io:host-gateway"
      - "fourth.127.0.0.1.nip.io:host-gateway"

  node-2:
    image: ontotext/graphdb:10.8.11
    ports:
      - "7202:7202"
      - "7302:7302"
    environment:
      GDB_JAVA_OPTS: >-
        -Dgraphdb.auth.token.secret=123456
        -Dgraphdb.connector.port=7202
        -Dgraphdb.hostname=second.127.0.0.1.nip.io
    volumes:
      - "${GRAPHDB_LICENSE}:/opt/graphdb/home/conf/graphdb.license:ro"
    extra_hosts:
      - "first.127.0.0.1.nip.io:host-gateway"
      - "second.127.0.0.1.nip.io:host-gateway"
      - "third.127.0.0.1.nip.io:host-gateway"
      - "fourth.127.0.0.1.nip.io:host-gateway"

  node-3:
    image: ontotext/graphdb:10.8.11
    ports:
      - "7203:7203"
      - "7303:7303"
    environment:
      GDB_JAVA_OPTS: >-
        -Dgraphdb.auth.token.secret=123456
        -Dgraphdb.connector.port=7203
        -Dgraphdb.hostname=third.127.0.0.1.nip.io
    volumes:
      - "${GRAPHDB_LICENSE}:/opt/graphdb/home/conf/graphdb.license:ro"
    extra_hosts:
      - "first.127.0.0.1.nip.io:host-gateway"
      - "second.127.0.0.1.nip.io:host-gateway"
      - "third.127.0.0.1.nip.io:host-gateway"
      - "fourth.127.0.0.1.nip.io:host-gateway"

  node-4:
    image: ontotext/graphdb:10.8.11
    ports:
      - "7204:7204"
      - "7304:7304"
    environment:
      GDB_JAVA_OPTS: >-
        -Dgraphdb.auth.token.secret=123456
        -Dgraphdb.connector.port=7204
        -Dgraphdb.hostname=fourth.127.0.0.1.nip.io
    volumes:
      - "${GRAPHDB_LICENSE}:/opt/graphdb/home/conf/graphdb.license:ro"
    extra_hosts:
      - "first.127.0.0.1.nip.io:host-gateway"
      - "second.127.0.0.1.nip.io:host-gateway"
      - "third.127.0.0.1.nip.io:host-gateway"
      - "fourth.127.0.0.1.nip.io:host-gateway"

  minio:
    image: quay.io/minio/minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command:
      - server
      - /data
      - --console-address
      - ":9001"
